const crypto = require('crypto')

const PREFIX = '/api/owner/v1'
const MAX_LIMIT = 100
const attempts = new Map()
const revoked = new Map()

function b64(value) { return Buffer.from(value).toString('base64url') }
function equal(a, b) { const x = Buffer.from(String(a)); const y = Buffer.from(String(b)); return x.length === y.length && crypto.timingSafeEqual(x, y) }
function envList(name) { return String(process.env[name] || '').split(',').map(v => v.trim()).filter(Boolean) }
function validOwner(value) { const s = String(value || '').trim(); return /^\d{6,20}$/.test(s) ? s : '' }
function owners() { return new Set(envList('OWNER_API_OWNERS').map(validOwner).filter(Boolean)) }
function cookie(req, name) { try { const value = String(req.headers.cookie || '').split(';').map(v => v.trim()).find(v => v.startsWith(`${name}=`)); return value ? decodeURIComponent(value.slice(name.length + 1)) : '' } catch { return '' } }
function sign(payload) { return `${payload}.${crypto.createHmac('sha256', process.env.OWNER_SESSION_SECRET || '').update(payload).digest('base64url')}` }
function parseSession(req) {
  const raw = cookie(req, 'botwa_owner'); if (!raw || raw.length > 2048 || !process.env.OWNER_SESSION_SECRET) return null
  const at = raw.lastIndexOf('.'); if (at < 1 || !equal(sign(raw.slice(0, at)), raw)) return null
  try { const s = JSON.parse(Buffer.from(raw.slice(0, at), 'base64url').toString()); return s.exp > Date.now() && owners().has(s.owner) && !revoked.has(s.nonce) ? s : null } catch { return null }
}
function originAllowed(req) { const origin = req.headers.origin; return Boolean(origin && envList('OWNER_API_ORIGINS').includes(origin)) }
function fail(res, status, code, message, details) { return res.status(status).json({ success: false, error: { code, message, ...(details ? { details } : {}) } }) }
function text(value, max = 120) { return String(value == null ? '' : value).trim().slice(0, max) }
function positive(value, fallback, max = MAX_LIMIT) { const n = Number.parseInt(value, 10); return Number.isFinite(n) ? Math.min(Math.max(n, 1), max) : fallback }
function page(items, req) { const limit = positive(req.query.limit, 20); const current = positive(req.query.page, 1, 100000); return { items: items.slice((current - 1) * limit, current * limit), pagination: { page: current, limit, total: items.length, pages: Math.max(1, Math.ceil(items.length / limit)) } } }
function redactId(id) { const s = String(id || '').replace(/@s\.whatsapp\.net$/i, ''); return `••••${s.slice(-4)}` }
function normalizeUser(id) { const raw = String(id || '').trim(); const digits = raw.replace(/@s\.whatsapp\.net$/i, ''); return /^\d{6,20}$/.test(digits) ? `${digits}@s.whatsapp.net` : '' }
function productView(id, p) { const stock = Array.isArray(p.stok) ? p.stok : Array.isArray(p.data) ? p.data : []; return { id, name: text(p.name || p.nama || p.judul || id), description: text(p.desc || p.description, 2000), snk: text(p.snk, 4000), prices: { bronze: Number(p.priceB ?? p.price ?? p.harga ?? 0), silver: Number(p.priceS ?? p.price_silver ?? p.price ?? p.harga ?? 0), gold: Number(p.priceG ?? p.price_gold ?? p.price ?? p.harga ?? 0) }, stock: stock.length, status: stock.length > 5 ? 'tersedia' : stock.length ? 'menipis' : 'habis' } }
function stockId(value) { return crypto.createHash('sha256').update(String(value)).digest('hex').slice(0, 20) }
function legacyOverviewAmount(row) { const m = row.meta || row; return Number.parseInt(m.totalBayar, 10) || Number.parseInt(m.price, 10) * (Number.parseInt(m.jumlah, 10) || 1) || 0 }
function legacyFinanceAmount(row) { const m = row.meta || row; return Number.parseInt(m.totalBayar, 10) || 0 }
function exactRef(value, max = 120) { const s=String(value == null ? '' : value).trim(); return s && s.length<=max && !/[\x00-\x1f\x7f]/.test(s) ? s : null }
function transaction(row) { const m = row.meta || row; const ref = exactRef(row.ref_id || m.ref_id || m.reffId || m.order_id || m.orderId); return { refId: ref, detailAvailable: Boolean(ref), userId: redactId(row.user_id || m.user_id || m.user), amount: legacyOverviewAmount(row), status: text(row.status || m.status || 'unknown', 32), productId: exactRef(m.product_id ?? m.kode ?? m.id), product: text(m.name || m.product || m.produk), payment: text(m.metodeBayar || m.payment_type || m.payment_method, 40), createdAt: row.created_at || m.date || m.createdAt || null } }
const DAY_MS = 86400000
function dayNumber(s) { const m = /^(\d{4})-(\d{2})-(\d{2})$/.exec(String(s || '')); if (!m) return null; const n = Date.UTC(+m[1], +m[2]-1, +m[3]); const d = new Date(n); return d.getUTCFullYear()===+m[1] && d.getUTCMonth()===+m[2]-1 && d.getUTCDate()===+m[3] ? n/DAY_MS : null }
function dayString(n) { return new Date(n*DAY_MS).toISOString().slice(0,10) }
function wibToday(now = new Date()) { return new Date(now.getTime()+7*3600000).toISOString().slice(0,10) }
function transactionTime(value) { if (typeof value==='number') return Number.isFinite(value)?value:null; if(typeof value!=='string'||!value)return null; const prefix=value.slice(0,10); if(/^\d{4}-\d{2}-\d{2}$/.test(prefix)&&dayNumber(prefix)==null)return null; if(/^\d{4}-\d{2}-\d{2}$/.test(value))return Date.parse(`${value}T00:00:00+07:00`); if(!/(?:Z|[+-]\d{2}:?\d{2})$/i.test(value))return null; const n=Date.parse(value);return Number.isFinite(n)?n:null }
function transactionDay(value) { const n=transactionTime(value); return n==null?null:new Date(n+7*3600000).toISOString().slice(0,10) }
function parseRange(query, defaults = true) { const hasFrom = query.from != null && query.from !== ''; const hasTo = query.to != null && query.to !== ''; if (!hasFrom && !hasTo && !defaults) return { allTime:true }; if (hasFrom !== hasTo) return { error:'from dan to harus diberikan bersama' }; const today=dayNumber(wibToday()); const to=hasTo?dayNumber(query.to):today; const from=hasFrom?dayNumber(query.from):to-29; if (from==null||to==null) return { error:'Tanggal harus berformat YYYY-MM-DD dan nyata' }; const days=to-from+1; if(from>to||days>366||to>today) return { error:'Rentang tanggal tidak valid, maksimum 366 hari, dan tidak boleh ke masa depan' }; return { from:dayString(from),to:dayString(to),fromDay:from,toDay:to,days,timezone:'Asia/Jakarta' } }
function inRange(t, range) { if (range.allTime) return true; const d=transactionDay(t.createdAt); return d && d>=range.from && d<=range.to }
function groupRows(rows, key) { const out=new Map(); for(const t of rows){const k=text(t[key]||'unknown',120)||'unknown'; const x=out.get(k)||{key:k,count:0,recordedAmount:0};x.count++;x.recordedAmount+=t.amount;out.set(k,x)} return [...out.values()] }
function requireMutation(req, res, confirmation) { if (!text(req.headers['idempotency-key'], 128)) { fail(res, 400, 'IDEMPOTENCY_REQUIRED', 'Idempotency-Key diperlukan'); return false } if (!text(req.body && req.body.reason, 300)) { fail(res, 400, 'VALIDATION_ERROR', 'Alasan diperlukan'); return false } if (text(req.body && req.body.confirmation, 100) !== confirmation) { fail(res, 400, 'CONFIRMATION_REQUIRED', `Konfirmasi harus ${confirmation}`); return false } return true }
function validIdr(value, positiveOnly = false) { return Number.isSafeInteger(value) && Number.isFinite(value) && (positiveOnly ? value > 0 : value >= 0) }
function safeHost(host) { return { id: crypto.createHash('sha256').update(host.accountId).digest('hex').slice(0, 16), label: host.label, timezone: host.timezone, exp: host.exp, concurrentMeetings: host.concurrentMeetings, enabled: !host.disabledAt, disabledReason: host.disabledReason || null } }

module.exports = function mountOwnerApi(app, deps = {}) {
  const { pg, getDbInstance, usePg = true, redis } = deps
  const zoom = deps.zoom || require('../lib/zoom-pool')
  const collectHealth = deps.collectHealth || require('../lib/health').collectHealth
  const anomalyReport = deps.anomalyReport || require('../lib/anomalies').report
  let cachedSnapshot, snapshotAt=0, snapshotPending; async function snapshot() { if(cachedSnapshot && Date.now()-snapshotAt<5000)return cachedSnapshot; if(snapshotPending)return snapshotPending; snapshotPending=(async()=>{const db=await getDbInstance();if(db.load)await db.load();cachedSnapshot=db.data||{};snapshotAt=Date.now();return cachedSnapshot;})();try{return await snapshotPending}finally{snapshotPending=null} }
  async function audit(req, action, target, detail = {}) { const row = { id: `AUD-${crypto.randomUUID()}`, action, target, owner: req.owner, reason: text(req.body && req.body.reason, 300), requestId: text(req.headers['x-request-id'], 100) || null, at: new Date().toISOString(), ...detail }; if (deps.audit) await deps.audit(row); else console.info(JSON.stringify({ type: 'owner_audit', ...row })); return row }
  function asyncRoute(fn) { return (req, res, next) => Promise.resolve(fn(req, res)).catch(next) }

  app.use(PREFIX, (req,res,next) => { res.setHeader('Cache-Control','private, no-store'); res.setHeader('X-Content-Type-Options','nosniff'); if(Buffer.byteLength(JSON.stringify(req.body||{}))>65536) return fail(res,413,'PAYLOAD_TOO_LARGE','Payload terlalu besar'); next(); });
  app.post(`${PREFIX}/auth/login`, (req, res) => {
    if (!originAllowed(req)) return fail(res, 403, 'ORIGIN_FORBIDDEN', 'Origin tidak diizinkan')
    const key = req.ip || 'unknown'; const now = Date.now(); for(const [k,v] of attempts) if(now-v.since>900000) attempts.delete(k); if(attempts.size>10000) return fail(res,429,'RATE_LIMITED','Terlalu banyak percobaan'); const state = attempts.get(key) || { count: 0, since: now }; if (now - state.since > 900000) { state.count = 0; state.since = now }
    if (state.count >= 8) return fail(res, 429, 'RATE_LIMITED', 'Terlalu banyak percobaan')
    const owner = validOwner(req.body && req.body.owner); const configured = process.env.OWNER_API_SECRET || ''
    if (!configured || !process.env.OWNER_SESSION_SECRET || !owners().size || !owners().has(owner) || !equal(req.body && req.body.secret, configured)) { state.count++; attempts.set(key, state); return fail(res, 401, 'INVALID_CREDENTIALS', 'Kredensial tidak valid') }
    attempts.delete(key); const exp = now + 8 * 3600000; const csrf = crypto.randomBytes(24).toString('base64url'); const payload = b64(JSON.stringify({ owner, exp, nonce: crypto.randomUUID(), csrf })); const token = sign(payload); const secure = '; Secure'
    res.append('Set-Cookie', `botwa_owner=${encodeURIComponent(token)}; HttpOnly; SameSite=Strict; Path=${PREFIX}; Max-Age=28800${secure}`); res.append('Set-Cookie', `botwa_csrf=${csrf}; SameSite=Strict; Path=${PREFIX}; Max-Age=28800${secure}`); res.json({ success: true, data: { owner: redactId(owner), csrfToken: csrf, expiresAt: new Date(exp).toISOString() } })
  })
  app.use(PREFIX, (req, res, next) => { res.setHeader('Cache-Control', 'no-store'); const actualSize = req.rawBody ? req.rawBody.length : Buffer.byteLength(JSON.stringify(req.body || {})); if (actualSize > 65536 || Number(req.headers['content-length'] || 0) > 65536) return fail(res, 413, 'PAYLOAD_TOO_LARGE', 'Payload melebihi 64 KiB'); if (!originAllowed(req)) return fail(res, 403, 'ORIGIN_FORBIDDEN', 'Origin tidak diizinkan'); const session = parseSession(req); if (!session) return fail(res, 401, 'AUTH_REQUIRED', 'Sesi owner diperlukan'); req.owner = session.owner; req.ownerSession = session; if (!['GET', 'HEAD', 'OPTIONS'].includes(req.method) && (!session.csrf || !cookie(req, 'botwa_csrf') || !equal(session.csrf, cookie(req, 'botwa_csrf')) || !equal(session.csrf, req.headers['x-csrf-token']))) return fail(res, 403, 'CSRF_INVALID', 'CSRF tidak valid'); next() })
  app.get(`${PREFIX}/auth/me`, (req, res) => res.json({ success: true, data: { owner: redactId(req.owner), role: 'owner', csrfToken: req.ownerSession.csrf, expiresAt: new Date(req.ownerSession.exp).toISOString() } }))
  app.post(`${PREFIX}/auth/logout`, asyncRoute(async (req, res) => { revoked.set(req.ownerSession.nonce, req.ownerSession.exp); for (const [k, exp] of revoked) if (exp <= Date.now()) revoked.delete(k); try { await audit(req, 'auth.logout', req.owner); } catch {}; res.setHeader('Set-Cookie', ['botwa_owner=; HttpOnly; SameSite=Strict; Path=/api/owner/v1; Max-Age=0', 'botwa_csrf=; SameSite=Strict; Path=/api/owner/v1; Max-Age=0']); res.json({ success: true, data: { loggedOut: true } }) }))

  const blockedWrite = (reason) => (req, res) => fail(res, 503, 'UNSUPPORTED', reason)
  app.use(PREFIX, (req,res,next) => ['GET','HEAD','OPTIONS'].includes(req.method) ? next() : fail(res,503,'UNSUPPORTED','Aksi administratif belum diaktifkan; data bisnis tidak diubah.'))
  app.use(`${PREFIX}/products`, (req, res, next) => ['GET', 'HEAD'].includes(req.method) ? next() : blockedWrite('Write produk/stok dinonaktifkan: bot dapat menyimpan snapshot stale dan menimpa perubahan.')(req, res))
  app.use(`${PREFIX}/users/:id/balance-adjustments`, blockedWrite('Penyesuaian saldo dinonaktifkan sampai reservasi OTP dan idempotensi konkuren dijamin atomik.'))

  app.get(`${PREFIX}/overview`, asyncRoute(async (req, res) => { const db = await snapshot(); const tx = (db.transaksi || []).map(transaction); const products = Object.values(db.produk || {}); res.json({ success: true, data: { users: Object.keys(db.users || {}).length, products: products.length, stock: products.reduce((n, p) => n + (Array.isArray(p.stok)?p.stok:Array.isArray(p.data)?p.data:[]).length, 0), transactions: tx.length, revenue: tx.reduce((n, t) => n + t.amount, 0), revenueDefinition: 'Total transaksi tercatat: totalBayar, atau price × jumlah jika totalBayar kosong; semua status.', revenuePeriod: 'all_time', confirmedAmount: tx.filter(t => ['completed','success'].includes(t.status.toLowerCase())).reduce((n, t) => n + t.amount, 0), generatedAt: new Date().toISOString() } }) }))
  function rangeOrFail(req,res,defaults=true){const r=parseRange(req.query,defaults);if(r.error){fail(res,400,'VALIDATION_ERROR',r.error);return null}return r}
  function productStats(rows,id){const matches=rows.filter(t=>t.productId===id);return { salesCount:matches.reduce((n,t)=>n+(Number.parseInt((t._raw.meta||t._raw).jumlah,10)||1),0), recordedRevenue:matches.reduce((n,t)=>n+t.amount,0), rows:matches }}
  const analytics=asyncRoute(async (req,res)=>{const range=rangeOrFail(req,res);if(!range)return;const db=await snapshot();const all=(db.transaksi||[]).map(r=>({...transaction(r),_raw:r}));const dated=all.map(t=>({...t,_day:transactionDay(t.createdAt),_time:transactionTime(t.createdAt)}));const rows=dated.filter(t=>t._day&&t._day>=range.from&&t._day<=range.to);const previous={from:dayString(range.fromDay-range.days),to:dayString(range.fromDay-1)};const prior=dated.filter(t=>t._day&&t._day>=previous.from&&t._day<=previous.to);const totals=x=>({recordedAmount:x.reduce((n,t)=>n+t.amount,0),count:x.length,confirmedAmount:x.filter(t=>['completed','success'].includes(t.status.toLowerCase())).reduce((n,t)=>n+t.amount,0)});const current=totals(rows),before=totals(prior);current.average=current.count?current.recordedAmount/current.count:0;before.average=before.count?before.recordedAmount/before.count:0;const comparison={};for(const k of ['recordedAmount','count','confirmedAmount','average'])comparison[k]={previous:before[k],changePercent:before[k]===0?null:(current[k]-before[k])*100/before[k]};const byDay=new Map();for(const t of rows){const x=byDay.get(t._day)||[];x.push(t);byDay.set(t._day,x)}const series=[];for(let d=range.fromDay;d<=range.toDay;d++){const date=dayString(d);series.push({date,...totals(byDay.get(date)||[])})}const productDb=db.produk||{};const products=groupRows(rows.filter(t=>t.productId),'productId').map(x=>{const own=Object.prototype.hasOwnProperty.call(productDb,x.key);return {...x,productId:x.key,name:(own&&productView(x.key,productDb[x.key]).name)||rows.find(t=>t.productId===x.key)?.product||x.key}}).sort((a,b)=>b.recordedAmount-a.recordedAmount).slice(0,10);res.json({success:true,data:{range:{from:range.from,to:range.to,days:range.days,timezone:range.timezone},previousRange:previous,kpis:{...current,comparison},series,statusGroups:groupRows(rows,'status'),paymentGroups:groupRows(rows,'payment'),topProducts:products,recentTransactions:rows.slice().sort((a,b)=>b._time-a._time).slice(0,10).map(({_raw,_day,_time,...t})=>t),warnings:{invalidOrMissingDateCount:dated.filter(t=>!t._day).length,missingProductIdCount:rows.filter(t=>!t.productId).length}}})})
  app.get(`${PREFIX}/daily`,(req,res,next)=>{if(!req.query.date)return fail(res,400,'VALIDATION_ERROR','date wajib');req.query.from=req.query.date;req.query.to=req.query.date;return analytics(req,res,next)})
  app.get(`${PREFIX}/analytics`,analytics)
  app.get(`${PREFIX}/products`, asyncRoute(async (req, res) => { const range=rangeOrFail(req,res);if(!range)return;const db = await snapshot(); const q = text(req.query.search).toLowerCase(); const tx=(db.transaksi||[]).map(r=>({...transaction(r),_raw:r})).filter(t=>inRange(t,range));let rows=Object.entries(db.produk||{}).map(([id,p])=>{const s=productStats(tx,id);return {...productView(id,p),stats:{salesCount:s.salesCount,recordedRevenue:s.recordedRevenue},warnings:{missingProductMapCount:tx.filter(t=>!t.productId).length}}}).filter(p=>(!q||`${p.id} ${p.name}`.toLowerCase().includes(q))&&(!req.query.status||p.status===req.query.status));const sort=['name','stock','sales','revenue'].includes(req.query.sort)?req.query.sort:'name';rows.sort((a,b)=>sort==='name'?a.name.localeCompare(b.name):sort==='stock'?a.stock-b.stock:sort==='sales'?a.stats.salesCount-b.stats.salesCount:a.stats.recordedRevenue-b.stats.recordedRevenue);if(req.query.order==='desc')rows.reverse();res.json({ success: true, data: page(rows, req) }) }))
  app.get(`${PREFIX}/products/:id`, asyncRoute(async (req, res) => { if(!req.params.id||req.params.id.length>120||/[\x00-\x1f\x7f]/.test(req.params.id))return fail(res,400,'VALIDATION_ERROR','ID produk tidak valid');const range=rangeOrFail(req,res);if(!range)return;const db=await snapshot();const p=db.produk&&Object.prototype.hasOwnProperty.call(db.produk,req.params.id)&&db.produk[req.params.id];if(!p)return fail(res,404,'NOT_FOUND','Produk tidak ditemukan');const tx=(db.transaksi||[]).map(r=>({...transaction(r),_raw:r})).filter(t=>inRange(t,range));const s=productStats(tx,req.params.id);res.json({success:true,data:{...productView(req.params.id,p),stats:{salesCount:s.salesCount,recordedRevenue:s.recordedRevenue},warnings:{missingProductMapCount:tx.filter(t=>!t.productId).length},latestTransactions:s.rows.slice().reverse().slice(0,10).map(({_raw,...t})=>t)}}) }))
  app.post(`${PREFIX}/products`, asyncRoute(async (req, res) => { if (!requireMutation(req, res, 'CREATE')) return; const id = text(req.body.id, 50); if (!/^[A-Za-z0-9_-]{1,50}$/.test(id) || !text(req.body.name)) return fail(res, 400, 'VALIDATION_ERROR', 'ID/nama produk tidak valid'); const data = { name: text(req.body.name), desc: text(req.body.description, 2000), snk: text(req.body.snk, 4000), price: Number(req.body.prices && req.body.prices.bronze), price_silver: Number(req.body.prices && req.body.prices.silver), price_gold: Number(req.body.prices && req.body.prices.gold), stok: [] }; if (![data.price, data.price_silver, data.price_gold].every(v => validIdr(v))) return fail(res, 400, 'VALIDATION_ERROR', 'Harga tidak valid'); const r = await pg.query('INSERT INTO produk(id,name,price,stock,data) VALUES($1,$2,$3,0,$4::jsonb) ON CONFLICT DO NOTHING RETURNING id', [id, data.name, data.price, JSON.stringify(data)]); if (!r.rowCount) return fail(res, 409, 'CONFLICT', 'Produk sudah ada'); await audit(req, 'product.create', id); res.status(201).json({ success: true, data: productView(id, data) }) }))
  app.patch(`${PREFIX}/products/:id`, asyncRoute(async (req, res) => { if (!requireMutation(req, res, 'UPDATE')) return; const patch = req.body; if (patch.prices && ![patch.prices.bronze, patch.prices.silver, patch.prices.gold].map(Number).every(v => validIdr(v))) return fail(res, 400, 'VALIDATION_ERROR', 'Harga tidak valid'); const r = await pg.query(`UPDATE produk SET data=(data || $2::jsonb),name=COALESCE($3,name),price=COALESCE($4,price) WHERE id=$1 RETURNING data`, [req.params.id, JSON.stringify({ ...(patch.name ? { name: text(patch.name) } : {}), ...(patch.description != null ? { desc: text(patch.description, 2000) } : {}), ...(patch.snk != null ? { snk: text(patch.snk, 4000) } : {}), ...(patch.prices ? { price: Number(patch.prices.bronze), price_silver: Number(patch.prices.silver), price_gold: Number(patch.prices.gold) } : {}) }), patch.name ? text(patch.name) : null, patch.prices ? Number(patch.prices.bronze) : null]); if (!r.rowCount) return fail(res, 404, 'NOT_FOUND', 'Produk tidak ditemukan'); await audit(req, 'product.update', req.params.id); res.json({ success: true, data: productView(req.params.id, r.rows[0].data) }) }))
  app.delete(`${PREFIX}/products/:id`, asyncRoute(async (req, res) => { if (!requireMutation(req, res, `DELETE ${req.params.id}`)) return; const r = await pg.query(`DELETE FROM produk WHERE id=$1 AND jsonb_array_length(COALESCE(data->'stok','[]'::jsonb))=0 RETURNING id`, [req.params.id]); if (!r.rowCount) return fail(res, 409, 'CONFLICT', 'Produk tidak ada atau stok belum kosong'); await audit(req, 'product.delete', req.params.id); res.json({ success: true, data: { id: req.params.id, deleted: true } }) }))
  app.post(`${PREFIX}/products/:id/stock`, asyncRoute(async (req, res) => { if (!requireMutation(req, res, 'ADD')) return; const value = text(req.body.value, 2000); if (!value) return fail(res, 400, 'VALIDATION_ERROR', 'Nilai stok diperlukan'); const r = await pg.query(`UPDATE produk SET data=jsonb_set(data,'{stok}',COALESCE(data->'stok','[]'::jsonb)||to_jsonb($2::text)),stock=stock+1 WHERE id=$1 RETURNING data`, [req.params.id, value]); if (!r.rowCount) return fail(res, 404, 'NOT_FOUND', 'Produk tidak ditemukan'); await audit(req, 'stock.add', req.params.id, { stockId: stockId(value) }); res.status(201).json({ success: true, data: { id: stockId(value), preview: `${value.slice(0, 2)}••••` } }) }))
  async function mutateStock(req, res, remove) { if (!requireMutation(req, res, remove ? 'DELETE' : 'UPDATE')) return; const oldHash = req.params.stockId; const value = remove ? null : text(req.body.value, 2000); if (!remove && !value) return fail(res, 400, 'VALIDATION_ERROR', 'Nilai stok diperlukan'); const client = await pg.getClient(); try { await client.query('BEGIN'); const locked = await client.query('SELECT data FROM produk WHERE id=$1 FOR UPDATE', [req.params.id]); if (!locked.rowCount) { await client.query('ROLLBACK'); return fail(res, 404, 'NOT_FOUND', 'Produk tidak ditemukan') } const data = locked.rows[0].data || {}; const stock = Array.isArray(data.stok) ? data.stok : []; const index = stock.findIndex(v => stockId(v) === oldHash); if (index < 0) { await client.query('ROLLBACK'); return fail(res, 409, 'CONFLICT', 'Stok telah berubah atau terjual') } if (remove) stock.splice(index, 1); else stock[index] = value; data.stok = stock; await client.query('UPDATE produk SET data=$2::jsonb,stock=$3 WHERE id=$1', [req.params.id, JSON.stringify(data), stock.length]); await client.query('COMMIT'); await audit(req, remove ? 'stock.delete' : 'stock.update', req.params.id, { stockId: oldHash }); res.json({ success: true, data: { id: remove ? oldHash : stockId(value), deleted: remove } }) } catch (e) { await client.query('ROLLBACK'); throw e } finally { client.release() } }
  app.patch(`${PREFIX}/products/:id/stock/:stockId`, asyncRoute((req, res) => mutateStock(req, res, false))); app.delete(`${PREFIX}/products/:id/stock/:stockId`, asyncRoute((req, res) => mutateStock(req, res, true)))

  app.use(`${PREFIX}/users/:id`, (req, res, next) => normalizeUser(req.params.id) ? next() : fail(res, 400, 'VALIDATION_ERROR', 'User ID tidak valid'))
  app.get(`${PREFIX}/users`, asyncRoute(async (req, res) => { const db = await snapshot(); const q = text(req.query.search).toLowerCase(); const rows = Object.entries(db.users || {}).map(([id, u]) => ({ id, displayId: redactId(id), username: text(u.username), saldo: Number(u.saldo || 0), role: text(u.role || 'bronze', 24), active: u.isActive !== false })).filter(u => !q || `${u.id} ${u.username}`.toLowerCase().includes(q)); res.json({ success: true, data: page(rows, req) }) }))
  app.get(`${PREFIX}/users/:id`, asyncRoute(async (req, res) => { const id = normalizeUser(req.params.id); const r = await pg.query('SELECT user_id,saldo,role,data FROM users WHERE user_id=$1', [id]); if (!r.rowCount) return fail(res, 404, 'NOT_FOUND', 'User tidak ditemukan'); const u = r.rows[0]; res.json({ success: true, data: { id: u.user_id, displayId: redactId(u.user_id), saldo: Number(u.saldo), role: u.role, active: u.data.isActive !== false, pinConfigured: Boolean(u.data.pin) } }) }))
  app.patch(`${PREFIX}/users/:id/role`, asyncRoute(async (req, res) => { if (!requireMutation(req, res, 'UPDATE')) return; const role = text(req.body.role, 20); if (!['bronze', 'silver', 'gold'].includes(role)) return fail(res, 400, 'VALIDATION_ERROR', 'Role tidak valid'); const r = await pg.query('UPDATE users SET role=$2,data=jsonb_set(COALESCE(data,$3::jsonb),\'{role}\',to_jsonb($2::text)) WHERE user_id=$1 RETURNING user_id', [normalizeUser(req.params.id), role, '{}']); if (!r.rowCount) return fail(res, 404, 'NOT_FOUND', 'User tidak ditemukan'); await audit(req, 'user.role', r.rows[0].user_id, { role }); res.json({ success: true, data: { id: r.rows[0].user_id, role } }) }))
  app.post(`${PREFIX}/users/:id/pin`, asyncRoute(async (req, res) => { if (!requireMutation(req, res, 'RESET')) return; const pin = String(req.body.pin == null ? '' : req.body.pin).trim(); if (!/^\d{4,8}$/.test(pin)) return fail(res, 400, 'VALIDATION_ERROR', 'PIN harus 4-8 digit'); const r = await pg.query(`UPDATE users SET data=jsonb_set(COALESCE(data,'{}'::jsonb),'{pin}',to_jsonb($2::text)) WHERE user_id=$1 RETURNING user_id`, [normalizeUser(req.params.id), pin]); if (!r.rowCount) return fail(res, 404, 'NOT_FOUND', 'User tidak ditemukan'); await audit(req, 'user.pin_reset', r.rows[0].user_id); res.json({ success: true, data: { id: r.rows[0].user_id, pinConfigured: true } }) }))
  app.post(`${PREFIX}/users/:id/balance-adjustments`, asyncRoute(async (req, res) => { if (!requireMutation(req, res, 'ADJUST')) return; const amount = Number(req.body.amount); const operation = req.body.operation; if (!Number.isSafeInteger(amount) || amount <= 0 || !['credit', 'debit'].includes(operation)) return fail(res, 400, 'VALIDATION_ERROR', 'Nominal/operasi tidak valid'); const id = `OWN-${crypto.createHash('sha256').update(req.headers['idempotency-key']).digest('hex')}`; const userId = normalizeUser(req.params.id); const client = await pg.getClient(); try { await client.query('BEGIN'); const prior = await client.query('SELECT before_balance,after_balance,amount,action FROM saldo_history WHERE id=$1', [id]); if (prior.rowCount) { await client.query('COMMIT'); const p = prior.rows[0]; return res.json({ success: true, data: { id, userId, operation: p.action, amount: Number(p.amount), before: Number(p.before_balance), after: Number(p.after_balance), duplicate: true } }) } const u = await client.query('SELECT saldo FROM users WHERE user_id=$1 FOR UPDATE', [userId]); if (!u.rowCount) { await client.query('ROLLBACK'); return fail(res, 404, 'NOT_FOUND', 'User tidak ditemukan') } const before = Number(u.rows[0].saldo); const after = before + (operation === 'credit' ? amount : -amount); if (after < 0) { await client.query('ROLLBACK'); return fail(res, 409, 'INSUFFICIENT_BALANCE', 'Saldo tidak cukup') } await client.query('UPDATE users SET saldo=$2 WHERE user_id=$1', [userId, after]); await client.query(`INSERT INTO saldo_history(id,user_id,raw_user_id,action,method,amount,before_balance,after_balance,actor,notes,source,meta) VALUES($1,$2,$2,$3,'owner_api',$4,$5,$6,$7,$8,'owner_api',$9::jsonb)`, [id, userId, operation, amount, before, after, req.owner, text(req.body.reason, 300), JSON.stringify({ requestId: text(req.headers['x-request-id'], 100) || null })]); await client.query('COMMIT'); await audit(req, `balance.${operation}`, userId, { ledgerId: id, amount, before, after }); res.status(201).json({ success: true, data: { id, userId, operation, amount, before, after, duplicate: false } }) } catch (e) { await client.query('ROLLBACK'); throw e } finally { client.release() } }))
  app.get(`${PREFIX}/users/:id/ledger`, asyncRoute(async (req, res) => { const limit = positive(req.query.limit, 20); const offset = (positive(req.query.page, 1, 100000) - 1) * limit; const id = normalizeUser(req.params.id); const r = await pg.query('SELECT id,action,amount,before_balance,after_balance,actor,notes,created_at,count(*) OVER()::int total FROM saldo_history WHERE user_id=$1 ORDER BY created_at DESC LIMIT $2 OFFSET $3', [id, limit, offset]); res.json({ success: true, data: { items: r.rows.map(x => ({ id: x.id, action: x.action, amount: Number(x.amount), before: Number(x.before_balance), after: Number(x.after_balance), actor: redactId(x.actor), notes: x.notes, createdAt: x.created_at })), pagination: { page: offset / limit + 1, limit, total: r.rows[0]?.total || 0, pages: Math.max(1, Math.ceil((r.rows[0]?.total || 0) / limit)) } } }) }))

  app.get(`${PREFIX}/transactions`, asyncRoute(async (req, res) => { const range=rangeOrFail(req,res,false);if(!range)return;const db = await snapshot(); const q = text(req.query.search).toLowerCase(); const status = text(req.query.status, 32).toLowerCase(); const productId=text(req.query.productId,120);const rows = (db.transaksi || []).map(transaction).reverse().filter(t => inRange(t,range)&&(!productId||t.productId===productId)&&(!q || Object.values(t).join(' ').toLowerCase().includes(q)) && (!status || t.status.toLowerCase() === status)); res.json({ success: true, data: page(rows, req) }) }))
  app.get(`${PREFIX}/transactions/:refId`, asyncRoute(async (req, res) => { const db = await snapshot(); const found = (db.transaksi || []).map(transaction).find(t => t.refId === req.params.refId); return found ? res.json({ success: true, data: found }) : fail(res, 404, 'NOT_FOUND', 'Transaksi tidak ditemukan') }))
  app.get(`${PREFIX}/finance`, asyncRoute(async (req, res) => { const db = await snapshot(); const rows = db.transaksi || []; const tx = rows.map(transaction); const byStatus = {}; tx.forEach(t => { byStatus[t.status] = (byStatus[t.status] || 0) + 1 }); res.json({ success: true, data: { gross: tx.reduce((n, t) => n + t.amount, 0), legacyFinanceTotal: rows.reduce((n, row) => n + legacyFinanceAmount(row), 0), confirmedAmount: tx.filter(t => ['completed','success'].includes(t.status.toLowerCase())).reduce((n, t) => n + t.amount, 0), metricDefinition: 'gross memakai semantik overview legacy: totalBayar, atau price × jumlah jika kosong; semua status.', legacyFinanceDefinition: 'Total finance legacy: totalBayar saja; semua status.', period: 'all_time', count: tx.length, byStatus } }) }))
  app.get(`${PREFIX}/deposits-payments`, asyncRoute(async (req, res) => { const db = await snapshot(); const rows = [...Object.values(db.orderDeposit || {}), ...Object.values(db.order || {})].slice(0, 100).map((o, i) => ({ id: text(o.orderId || o.id || `order-${i}`), status: text(o.status || o.state || 'unknown', 32), amount: Number(o.amount || o.total || 0), createdAt: o.createdAt || null })); res.json({ success: true, data: { items: rows, pagination: { page: 1, limit: 100, total: rows.length, pages: 1 } } }) }))
  app.get(`${PREFIX}/services-otp`, asyncRoute(async (req, res) => { const r = await pg.query('SELECT state,count(*)::int count FROM otp_orders GROUP BY state ORDER BY state'); res.json({ success: true, data: { total: r.rows.reduce((n, x) => n + x.count, 0), byState: Object.fromEntries(r.rows.map(x => [x.state, x.count])) } }) }))

  app.get(`${PREFIX}/zoom`, (req, res) => res.json({ success: true, data: { tiers: zoom.VALID_TIERS.map(tier => { const hosts = zoom.loadPool(tier); return { tier, hosts: hosts.length, enabled: hosts.filter(h => !h.disabledAt).length, disabled: hosts.filter(h => h.disabledAt).length } }) } }))
  app.get(`${PREFIX}/zoom/:tier/hosts`, (req, res) => { const tier = Number(req.params.tier); if (!zoom.isValidTier(tier)) return fail(res, 400, 'VALIDATION_ERROR', 'Tier tidak valid'); res.json({ success: true, data: { items: zoom.loadPool(tier).map(safeHost) } }) })
  function hostById(tier, id) { return zoom.loadPool(tier).find(h => safeHost(h).id === id) }
  app.post(`${PREFIX}/zoom/:tier/hosts`, asyncRoute(async (req, res) => { if (!requireMutation(req, res, 'CREATE')) return; const tier = Number(req.params.tier); const host = { label: text(req.body.label), accountId: text(req.body.accountId, 200), clientId: text(req.body.clientId, 200), clientSecret: text(req.body.clientSecret, 500), userId: text(req.body.userId || 'me', 200), timezone: text(req.body.timezone, 80) || null, concurrentMeetings: Number(req.body.concurrentMeetings || 1), exp: text(req.body.exp, 10) || null }; if (!zoom.isValidTier(tier) || !host.label || !host.accountId || !host.clientId || !host.clientSecret) return fail(res, 400, 'VALIDATION_ERROR', 'Host/tier tidak valid'); const result = zoom.addHostToPool(tier, host); if (!result.ok) return fail(res, 409, 'CONFLICT', result.error); await audit(req, 'zoom.host_create', `${tier}:${host.label}`); res.status(201).json({ success: true, data: safeHost(result.host || host) }) }))
  app.delete(`${PREFIX}/zoom/:tier/hosts/:hostId`, asyncRoute(async (req, res) => { if (!requireMutation(req, res, 'DELETE')) return; const tier = Number(req.params.tier); const host = hostById(tier, req.params.hostId); if (!host) return fail(res, 404, 'NOT_FOUND', 'Host tidak ditemukan'); const result = zoom.removeHostFromPool(tier, { accountId: host.accountId }); if (!result.ok) return fail(res, 409, 'CONFLICT', result.error); await audit(req, 'zoom.host_delete', `${tier}:${host.label}`); res.json({ success: true, data: { id: req.params.hostId, deleted: true } }) }))
  app.post(`${PREFIX}/zoom/:tier/hosts/:hostId/enable`, asyncRoute(async (req, res) => { if (!requireMutation(req, res, 'ENABLE')) return; const tier = Number(req.params.tier); const host = hostById(tier, req.params.hostId); if (!host) return fail(res, 404, 'NOT_FOUND', 'Host tidak ditemukan'); const result = zoom.enableHost(tier, { accountId: host.accountId }); if (!result || !result.ok || !result.host) return fail(res, 409, 'PROVIDER_ERROR', 'Host tidak dapat diaktifkan'); await audit(req, 'zoom.host_enable', `${tier}:${host.label}`); res.json({ success: true, data: safeHost(result.host) }) }))
  app.get(`${PREFIX}/zoom/:tier/bookings`, asyncRoute(async (req, res) => { const result = await zoom.listBookings(Number(req.params.tier)); res.json({ success: true, data: { items: result.meetings.map(m => ({ id: String(m.id), topic: text(m.topic), startTime: m.start_time, durationMinutes: m.duration, hostId: m.hostAccountId ? crypto.createHash('sha256').update(m.hostAccountId).digest('hex').slice(0, 16) : null })), errors: result.errors.map(e => ({ label: e.label, error: 'Provider unavailable' })), source: result.source } }) }))
  app.post(`${PREFIX}/zoom/:tier/bookings`, asyncRoute(async (req, res) => { if (!requireMutation(req, res, 'CREATE')) return; const tier = Number(req.params.tier); const durationMinutes = Number(req.body.durationMinutes); const startAtUtcMs = Number(req.body.startAtUtcMs); if (!zoom.isValidTier(tier) || !text(req.body.topic) || !Number.isSafeInteger(durationMinutes) || durationMinutes < 1 || !Number.isFinite(startAtUtcMs)) return fail(res, 400, 'VALIDATION_ERROR', 'Booking tidak valid'); const result = await zoom.createMeetingOnFirstAvailable({ tier, topic: text(req.body.topic), startTimeIso: text(req.body.startTimeIso, 40), startAtUtcMs, durationMinutes, password: text(req.body.password, 20), timezone: text(req.body.timezone, 80), agenda: text(req.body.agenda, 1000) }); if (!result.ok) return fail(res, 409, 'PROVIDER_ERROR', 'Zoom tidak dapat membuat meeting', { reason: result.error }); await audit(req, 'zoom.booking_create', String(result.meeting.id), { tier }); res.status(201).json({ success: true, data: { id: String(result.meeting.id), topic: result.meeting.topic, joinUrl: result.meeting.join_url, tier } }) }))
  app.delete(`${PREFIX}/zoom/:tier/bookings/:meetingId`, asyncRoute(async (req, res) => { if (!requireMutation(req, res, 'DELETE')) return; const tier = Number(req.params.tier); const host = hostById(tier, text(req.body.hostId, 20)); if (!host) return fail(res, 404, 'NOT_FOUND', 'Host tidak ditemukan'); await zoom.deleteMeetingOn({ tier, hostAccountId: host.accountId, meetingId: req.params.meetingId }); await audit(req, 'zoom.booking_delete', req.params.meetingId, { tier }); res.json({ success: true, data: { id: req.params.meetingId, deleted: true } }) }))

  app.get(`${PREFIX}/configuration`, asyncRoute(async (req, res) => { const db = await snapshot(); const promo = db.promo || {}; res.json({ success: true, data: { database: usePg ? 'postgresql' : 'unsupported', promo: { enabled: Boolean(promo.enabled), groups: Array.isArray(promo.groups) ? promo.groups.length : 0, scheduleConfigured: Boolean(promo.time) }, integrations: { midtrans: Boolean(process.env.MIDTRANS_SERVER_KEY), xendit: Boolean(process.env.XENDIT_API_KEY), redis: Boolean(redis) } } }) }))
  app.get(`${PREFIX}/health`, asyncRoute(async (req, res) => res.json({ success: true, data: { health: await collectHealth({ pg, redis, pm2: true }), anomalies: await anomalyReport(pg), generatedAt: new Date().toISOString() } })))
  app.get(`${PREFIX}/audit`, asyncRoute(async (req, res) => { const r = deps.listAudit ? await deps.listAudit(req) : []; res.json({ success: true, data: page(r.map(x => ({ ...x, owner: redactId(x.owner) })), req) }) }))
  app.get(`${PREFIX}/capabilities`, (req, res) => res.json({ success: true, data: [{ area: 'products_stock', read: true, write: false, reason: 'Aksi administratif belum lolos verifikasi; rilis ini read-only.' }, { area: 'users_balance_roles_pin', read: true, write: false, reason: 'Aksi administratif belum lolos verifikasi; rilis ini read-only.' }, { area: 'transactions_payments', read: true, write: false, reason: 'Settlement tetap provider-only.' }, { area: 'zoom_hosts_bookings', read: true, write: false, reason: 'Aksi administratif belum lolos verifikasi; rilis ini read-only.' }, { area: 'otp_services', read: true, write: false, reason: 'OTP/provider purchase dilarang.' }, { area: 'arbitrary_exec_backup_delete', read: false, write: false, reason: 'Sengaja dilarang.' }] }))
  app.use(PREFIX, (req,res) => fail(res,404,'NOT_FOUND','Endpoint owner tidak ditemukan'));
  app.use(PREFIX, (err,req,res,next) => { if(res.headersSent)return next(err); console.error('[OWNER_API]', err && err.code || 'INTERNAL_ERROR'); return fail(res,500,'INTERNAL_ERROR','Data tidak dapat dimuat. Coba lagi nanti.'); });

}
